version: '3.9'
services:
  database:
    image: mysql:8
    command: mysqld --authentication_policy=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    container_name: '${APP_NAME}-db'
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    environment:
      - 'MYSQL_USER=${DATABASE_USER}'
      - 'MYSQL_PASSWORD=${DATABASE_PASSWORD}'
      - 'MYSQL_DATABASE=${APP_NAME}'
      - 'MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}'
  app:
    build: .
    container_name: '${APP_NAME}'
    ports:
      - '${API_PORT}:${API_PORT}'
    volumes:
      - '.:/usr/src/${APP_NAME}'
    links:
      - database
    depends_on:
      - database
    command: sh -c "/wait; yarn; yarn prisma migrate dev; yarn dev"
    environment:
      - 'WAIT_HOSTS=database:${DATABASE_PORT}'
      - WAIT_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=15
